In [107]:
import os
import pandas as pd
import numpy as np
pathresults = "../results/"
#pathresults = "/DUMUXDune27/DUMUX/dumux-rosi/python/paperSc/results/"
data_file_delimiter = ","

In [41]:
import os

def delete_files_in_folders(start_directory, folder_prefix, file_prefix):
    # Walk through the directory tree starting from start_directory
    for root, dirs, files in os.walk(start_directory):
        # Check if the directory name starts with the specified prefix
        if os.path.basename(root).startswith(folder_prefix):
            #print(f"Deleting files in folder: {root}")
            # Iterate over files in the directory
            
            for file in os.listdir(root):
                # Check if the file name starts with the specified prefix
                if file.startswith(file_prefix):
                    file_path = os.path.join(root, file)
                    # Delete the file
                    os.remove(file_path)
                    #print(f"Deleted file: {file_path}")

# Specify the directory where you want to start searching
start_directory = "../results"

# Specify the prefix for folders to search
folder_prefix = "noCss1"

# Specify the prefix for files to delete
file_prefix = "fpit"

# Call the function to delete files in folders with specified prefixes
delete_files_in_folders(start_directory, folder_prefix, file_prefix)


In [42]:
def getVal(mypath, filename, header="infer",names = None):
    fullpath = pathresults +mypath+filename
    if names is None:
        cst = pd.read_csv(fullpath,delimiter=data_file_delimiter, header = header).dropna(how= "all", axis=1)
    else:
        cst = pd.read_csv(fullpath,delimiter=data_file_delimiter, header = header, names = names).dropna(how= "all", axis=1)
    return cst


In [43]:
def get_last_line_as_numpy_array(file_path, dtype = int):
    with open(file_path, 'r') as file:
        # Read all lines
        lines = file.readlines()

        # Check if there are any lines in the file
        if not lines:
            raise ValueError("The file is empty")

        # Get the last line
        last_line = lines[-1].strip()

        # Split the last line by commas and convert to NumPy array
        array_from_last_line = np.array(last_line.split(','), dtype=dtype)

        return array_from_last_line

In [56]:
path2file = 'none_1440_14_10to11_20mn_0s_130/'
#'none_55_'+str(i)+'_10to11_20mn_0s_5/'# 'fixeUpdatenone'+str(i)+'0dx_2dumux_10c_10.0to25.0_20mn_0s_192_100/'
tt = getVal(path2file, "time.txt",names= ['time','Qlight'])
time = tt.iloc[:,0]
if max(time) < 11: 
    exceptPset.append(i)
    print(14, (int((max(time)-10.)*24*10)/10), end ="h, ")

14 16.6h, 

In [123]:
exceptPset = []
for i in range(99):
    # path2file = pathresults + 'param99none'+str(i)+'0dx_2dumux_10c_10.0to11.0_20mn_0s_192_100/'
    path2file = 'PDECSbnone_1440_'+str(i)+'_10to11_20mn_0s_5/'
    #'none_55_'+str(i)+'_10to11_20mn_0s_5/'# 'fixeUpdatenone'+str(i)+'0dx_2dumux_10c_10.0to25.0_20mn_0s_192_100/'
    tt = getVal(path2file, "time.txt",names= ['time','Qlight'])
    time = tt.iloc[:,0]
    if max(time) < 11: 
        exceptPset.append(i)
        print(i, (int((max(time)-10.)*24*10)/10), end ="h, ")
print(len(exceptPset))

0


In [118]:
exceptPset = []
for i in range(99):
    # path2file = pathresults + 'param99none'+str(i)+'0dx_2dumux_10c_10.0to11.0_20mn_0s_192_100/'
    path2file = 'PDECSanone_1440_'+str(i)+'_10to11_20mn_0s_5/'
    #'none_55_'+str(i)+'_10to11_20mn_0s_5/'# 'fixeUpdatenone'+str(i)+'0dx_2dumux_10c_10.0to25.0_20mn_0s_192_100/'
    tt = getVal(path2file, "time.txt",names= ['time','Qlight'])
    time = tt.iloc[:,0]
    if max(time) >= 11: 
        exceptPset.append(i)
        print(i, end =", ")#, (int((max(time)-10.)*24*10)/10), end ="h, ")

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 91, 92, 93, 94, 95, 96, 97, 98, 

In [121]:
exceptPset = []
for i in range(99):
    # path2file = pathresults + 'param99none'+str(i)+'0dx_2dumux_10c_10.0to11.0_20mn_0s_192_100/'
    path2file = 'PDECSbnone_1440_'+str(i)+'_10to11_20mn_0s_5/'
    #'none_55_'+str(i)+'_10to11_20mn_0s_5/'# 'fixeUpdatenone'+str(i)+'0dx_2dumux_10c_10.0to25.0_20mn_0s_192_100/'
    tt = getVal(path2file, "time.txt",names= ['time','Qlight'])
    time = tt.iloc[:,0]
    if max(time) >= 11: 
        exceptPset.append(i)
        print(i, (int((max(time)-10.)*24*10)/10), end ="h, ")

76 24.0h, 77 24.0h, 78 24.0h, 84 24.0h, 85 24.0h, 89 24.0h, 91 24.0h, 

In [106]:
print( max(getVal('1d1dFHungnone_1440_5_10to25_20mn_0s_128/', "time.txt",names= ['time','Qlight']).iloc[:,0]),
       max(getVal('1d1dFHungearlyDry_1440_5_10to25_20mn_0s_128/', "time.txt",names= ['time','Qlight']).iloc[:,0]),
       max(getVal('1d1dFHunglateDry_1440_5_10to25_20mn_0s_128/', "time.txt",names= ['time','Qlight']).iloc[:,0]))

23.19444444444482 23.94444444444484 23.250000000000377


In [101]:
print( max(getVal('none_1440_5_10to25_20mn_0s_130/', "time.txt",names= ['time','Qlight']).iloc[:,0]),
       max(getVal('earlyDry_1440_5_10to25_20mn_0s_130/', "time.txt",names= ['time','Qlight']).iloc[:,0]),
       max(getVal('lateDry_1440_5_10to25_20mn_0s_130/', "time.txt",names= ['time','Qlight']).iloc[:,0]))

25.000000000000423 25.000000000000423 25.000000000000423


In [102]:
print( max(getVal('none_1440_84_10to25_20mn_0s_130/', "time.txt",names= ['time','Qlight']).iloc[:,0]),
       max(getVal('newSourceearlyDry_1440_84_10to25_20mn_0s_130/', "time.txt",names= ['time','Qlight']).iloc[:,0]),
       max(getVal('lateDry_1440_84_10to25_20mn_0s_130/', "time.txt",names= ['time','Qlight']).iloc[:,0]))

25.000000000000423 25.000000000000423 25.000000000000423


17.680555555555774 13.180555555555646 18.583333333333577
13.416666666666764 11.611111111111155 15.62500000000016

In [25]:
print(exceptPset)

[12, 13, 20, 22, 32, 39, 44, 61, 66, 67, 91]


In [21]:
exceptPset = [12, 13, 20, 22, 32, 39, 41, 44, 61, 66, 67, 91]
pSets = [ i for i in range(99) if i not in exceptPset]

In [23]:
repr(pSets)

'[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 40, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 62, 63, 64, 65, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 98]'

In [22]:
# get mean CS gradient at root tip per param set
pSet = 0
path2file = pathresults + 'param99none'+str(pSet)+'0dx_2dumux_10c_10.0to11.0_20mn_0s_192_100/'
rr = get_last_line_as_numpy_array(path2file+"root_segments_tips.txt")

In [23]:
rr

array([189, 190, 194, 195, 199, 200, 201, 202, 203, 204, 206, 207, 208,
       209, 210, 211, 212, 214, 215, 216, 217, 218, 220, 221, 222, 223,
       224, 225, 226, 227, 228, 230, 231, 232, 233, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263])

In [43]:

Ginits = np.full(len(rr),np.nan)
for idx, gId in enumerate(rr):
    #gId = rr[0]
    fileName = "Cyl_cellVol_"+str(gId)+".txt"
    cVol = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
    fileName = "Cyl_content1_"+str(gId)+".txt"
    Q1 = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
    fileName = "Cyl_coord_"+str(gId)+".txt"
    dofc = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
    konz = Q1/cVol #mol/cm3
    Ginits[idx] = (np.diff( Q1/cVol)/np.diff(dofc))[0]


In [45]:
print(Ginits, np.mean(Ginits))

[-4.18405430e-03 -4.18403557e-03 -4.67010211e-03 -4.28215454e-03
 -5.70142892e-03 -5.70158295e-03 -4.58699466e-03 -4.00835645e-03
 -3.85981046e-03 -4.14192118e-03 -3.69089594e-03 -3.66631095e-03
 -4.20314311e-03 -3.96875455e-03 -4.30927331e-03 -3.92226811e-03
 -3.85711383e-03 -4.29105929e-03 -4.01377126e-03 -3.99567016e-03
 -4.26913219e-03 -4.26920360e-03 -4.70562096e-03 -4.85062365e-03
 -3.46195642e-03 -4.02656656e-03 -3.04143988e-03 -3.01204638e-03
 -2.70356092e-03 -3.29955250e-03 -3.29954372e-03 -2.66794207e-03
 -3.08719762e-03 -2.68563033e-03 -2.88830719e-03 -2.98028751e-03
 -2.62990364e-03 -2.41328381e-03 -2.33147198e-03 -2.46626649e-03
 -2.84284199e-03 -2.62283311e-03 -1.82298749e-03 -1.15634427e-03
 -1.25991027e-03 -1.12749754e-03 -1.13207602e-03 -1.44104715e-03
 -1.22883686e-03 -1.28413301e-03 -1.23457341e-03 -1.09817795e-03
 -6.08245553e-04 -1.03084931e-03 -8.79155556e-04 -7.16134255e-04
 -8.62651125e-04 -6.90456606e-04 -5.16440130e-04 -3.05746925e-04
 -3.12101259e-04 -3.82006

In [54]:
GiniMeans = np.full(94,np.nan)
for pSet in range(94):
    path2file = pathresults + 'param99none'+str(pSet)+'0dx_2dumux_10c_10.0to11.0_20mn_0s_192_100/'
    rr = get_last_line_as_numpy_array(path2file+"root_segments_tips.txt")
    Ginits = np.full(len(rr),np.nan)
    print('\npSet',pSet, 'len(rr)',len(rr))
    for idx, gId in enumerate(rr):
        print('rootid',idx, end =", ")
        #gId = rr[0]
        fileName = "Cyl_cellVol_"+str(gId)+".txt"
        cVol = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
        fileName = "Cyl_content1_"+str(gId)+".txt"
        Q1 = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
        fileName = "Cyl_watercontent_"+str(gId)+".txt"
        theta = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
        fileName = "Cyl_coord_"+str(gId)+".txt"
        dofc = get_last_line_as_numpy_array(path2file+fileName, dtype = float)
        watVol = theta * cVol
        if False:
            konz = Q1/cVol #mol/cm3
        else:
            konz = Q1/watVol #mol/cm3
        Ginits[idx] = (np.diff( Q1/cVol)/np.diff(dofc))[0]
    GiniMeans[pSet] = np.mean(Ginits)


pSet 0 len(rr) 64
rootid 0, rootid 1, rootid 2, rootid 3, rootid 4, rootid 5, rootid 6, rootid 7, rootid 8, rootid 9, rootid 10, rootid 11, rootid 12, rootid 13, rootid 14, rootid 15, rootid 16, rootid 17, rootid 18, rootid 19, rootid 20, rootid 21, rootid 22, rootid 23, rootid 24, rootid 25, rootid 26, rootid 27, rootid 28, rootid 29, rootid 30, rootid 31, rootid 32, rootid 33, rootid 34, rootid 35, rootid 36, rootid 37, rootid 38, rootid 39, rootid 40, rootid 41, rootid 42, rootid 43, rootid 44, rootid 45, rootid 46, rootid 47, rootid 48, rootid 49, rootid 50, rootid 51, rootid 52, rootid 53, rootid 54, rootid 55, rootid 56, rootid 57, rootid 58, rootid 59, rootid 60, rootid 61, rootid 62, rootid 63, 
pSet 1 len(rr) 64
rootid 0, rootid 1, rootid 2, rootid 3, rootid 4, rootid 5, rootid 6, rootid 7, rootid 8, rootid 9, rootid 10, rootid 11, rootid 12, rootid 13, rootid 14, rootid 15, rootid 16, rootid 17, rootid 18, rootid 19, rootid 20, rootid 21, rootid 22, rootid 23, rootid 24, roo

In [50]:
GiniMeans # cm bulk soil

array([-0.00273641, -0.00202488, -0.00110574, -0.00290133, -0.0117381 ,
       -0.00089841, -0.00101927, -0.01887921, -0.00114931, -0.00284976,
       -0.00255431, -0.00162958, -0.00155745, -0.00335403, -0.00123175,
       -0.00403352, -0.00476118, -0.00125625, -0.00334636, -0.00550468,
       -0.00102479, -0.00108434, -0.00323606, -0.00584733, -0.00742803,
       -0.00631972, -0.00268303, -0.02192963, -0.00099997, -0.00220465,
       -0.0027132 , -0.00258839, -0.00146373, -0.0025704 , -0.01537164,
       -0.01031349, -0.00465631, -0.00428957, -0.00379463, -0.00198646,
       -0.00119395, -0.00952366, -0.00570905, -0.0129929 , -0.00159737,
       -0.00841427, -0.00791242, -0.027498  , -0.00225339, -0.01284041,
       -0.00974247, -0.01431414, -0.00558926, -0.00143575, -0.00219985,
       -0.0151841 , -0.02837099, -0.0035191 , -0.01370258, -0.0023766 ,
       -0.03128102, -0.00114655, -0.01412926, -0.00278364, -0.00786797,
       -0.00182411, -0.00560847, -0.00161786, -0.00152403, -0.00

In [55]:
GiniMeans # cm3 water

array([-0.00273641, -0.00202488, -0.00110574, -0.00290133, -0.0117381 ,
       -0.00089841, -0.00101927, -0.01887921, -0.00114931, -0.00284976,
       -0.00255431, -0.00162958, -0.00155745, -0.00335403, -0.00123175,
       -0.00403352, -0.00476118, -0.00125625, -0.00334636, -0.00550468,
       -0.00102479, -0.00108434, -0.00323606, -0.00584733, -0.00742803,
       -0.00631972, -0.00268303, -0.02192963, -0.00099997, -0.00220465,
       -0.0027132 , -0.00258839, -0.00146373, -0.0025704 , -0.01537164,
       -0.01031349, -0.00465631, -0.00428957, -0.00379463, -0.00198646,
       -0.00119395, -0.00952366, -0.00570905, -0.0129929 , -0.00159737,
       -0.00841427, -0.00791242, -0.027498  , -0.00225339, -0.01284041,
       -0.00974247, -0.01431414, -0.00558926, -0.00143575, -0.00219985,
       -0.0151841 , -0.02837099, -0.0035191 , -0.01370258, -0.0023766 ,
       -0.03128102, -0.00114655, -0.01412926, -0.00278364, -0.00786797,
       -0.00182411, -0.00560847, -0.00161786, -0.00152403, -0.00

In [51]:
import matplotlib.pyplot as plt

In [52]:
plt.hist(GiniMeans, bins=1, color='blue', edgecolor='black')

(array([94.]),
 array([-0.04292021, -0.00079219]),
 <BarContainer object of 1 artists>)

In [53]:

# Adding labels and title
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram Example')

# Displaying the plot
plt.show()